feature: added uuid type to table cell types
Sphereon-Opensource/UI-Components pull request #16
Opened 2023-09-21 13:59 UTC by sksadjad

added a new label for uuid. this label will show a truncated version of uuid and when hover, it shows the full uuid

2023-09-21 15:11 UTC, sksadjad commented
@nklomp pushed another commit to address your comment (also pushed a commit in the other repo)

2023-09-21 18:25 UTC, nklomp requested changes
Some small remarks for changes

2023-09-21 18:25 UTC, nklomp commented on packages/ssi-react/src/components/labels/SSITruncatedText/index.tsx
> +const SSITruncatedText: FC<Props> = (props: Props): ReactElement => {
Unless we already have a SSIText, suggest to rename this to SSIText. The fact that it can truncate is just a nice benefit, not the main featuture. It is about displaying text

2023-09-21 18:25 UTC, nklomp commented on packages/ssi-react/src/types/component/index.ts
> +  UUID = 'uuid'
Remove type

2023-09-21 18:25 UTC, nklomp commented on packages/ssi-react/src/types/component/index.ts
> +  truncationLength?: number
Add a comment about what it does

2023-09-22 06:58 UTC, sksadjad commented on packages/ssi-react/src/types/component/index.ts
> +  truncationLength?: number
added a comment

2023-09-22 06:58 UTC, sksadjad commented on packages/ssi-react/src/types/component/index.ts
> +  UUID = 'uuid'
removed

2023-09-22 06:58 UTC, sksadjad commented on packages/ssi-react/src/components/labels/SSITruncatedText/index.tsx
> +const SSITruncatedText: FC<Props> = (props: Props): ReactElement => {
changed to SSIText

2023-09-22 07:19 UTC, nklomp approved these changes

2023-09-22 07:19 UTC, merged