feature/DPP-61
Sphereon-Opensource/UI-Components pull request #17
Opened 2023-09-22 16:32 UTC by maikel-maas

2023-10-30 12:41 UTC, BtencateSphereon requested changes

2023-10-30 12:41 UTC, BtencateSphereon commented on packages/ssi-react/src/components/views/SSITableView/index.tsx
> +        width: '60px',
why is there a width and a height? the status component should scale based on the content, which it should already do

2023-10-30 12:41 UTC, BtencateSphereon commented on packages/ssi-react/src/components/views/SSITableView/index.tsx
> +        justifyContent: 'center'
this should already be handles by the component

2023-10-31 19:46 UTC, BtencateSphereon commented on packages/core/src/styles/ssi/colors.ts
> +  Done: '#000' // TODO I see it in the UI but not in the design, need to update it with the correct color
would be nice to create a ticket about this

2023-10-31 19:46 UTC, BtencateSphereon commented on packages/ssi-react/src/components/views/SSITableView/index.tsx
> +import {SSIStatusLabel} from "../../../index";
single quotes

2023-10-31 19:50 UTC, BtencateSphereon commented on packages/ssi-react/src/components/views/SSITableView/index.tsx
> +      return <SSIStatusLabel status={value as LabelStatus} />
should we not use the WorkFlowStatus as value for the column and then use it here?

2023-11-01 11:59 UTC, maikel-maas commented on packages/ssi-react/src/components/views/SSITableView/index.tsx
> +import {SSIStatusLabel} from "../../../index";
Fixed

2023-11-01 11:59 UTC, maikel-maas commented on packages/core/src/styles/ssi/colors.ts
> +  Done: '#000' // TODO I see it in the UI but not in the design, need to update it with the correct color
Fixed

2023-11-02 15:25 UTC, BtencateSphereon approved these changes

2023-11-02 15:27 UTC, merged