feat/DPP-92
Sphereon-Opensource/UI-Components pull request #31
Opened 2023-11-14 08:04 UTC by sksadjad

exposed an option for columns to enable onHover for text fields. in case of passing true, the complete text will be shown in case of hover

2023-11-14 09:10 UTC, BtencateSphereon requested changes

2023-11-14 09:10 UTC, BtencateSphereon commented on packages/ssi-react/src/components/views/SSITableView/index.tsx
> +const getCellFormatting = (type: TableCellType, value: any, truncationLength?: number, enableHover?: boolean): ReactElement => {
i would start moving these to an options type, so  truncationLength and enableHover

2023-11-14 09:23 UTC, maikel-maas commented on packages/ssi-react/src/components/views/SSITableView/index.tsx
> +const getCellFormatting = (type: TableCellType, value: any, truncationLength?: number, enableHover?: boolean): ReactElement => {
The list of parameters is increasing. Maybe it's time to make it an object?

2023-11-14 09:24 UTC, maikel-maas requested changes
Left a remak

2023-11-14 10:12 UTC, nklomp commented on packages/ssi-react/src/components/views/SSITableView/index.tsx
> +const getCellFormatting = (type: TableCellType, value: any, truncationLength?: number, enableHover?: boolean): ReactElement => {
Whenever you start introducing optionals always immediately go for an object, as that means you get really ugly calls with nulls in there, or cannot add a required option anymore without refactoring anyway

2023-11-14 10:12 UTC, nklomp commented on packages/ssi-react/src/components/views/SSITableView/index.tsx
> +const getCellFormatting = (type: TableCellType, value: any, truncationLength?: number, enableHover?: boolean): ReactElement => {
Whenever you start introducing optionals always immediately go for an object, as that means you get really ugly calls with nulls in there, or cannot add a required option anymore without refactoring anyway

2023-11-14 10:13 UTC, nklomp commented on packages/ssi-react/src/components/views/SSITableView/index.tsx
> +const getCellFormatting = (type: TableCellType, value: any, truncationLength?: number, enableHover?: boolean): ReactElement => {
Besides truncationLenght etc are clearly options to begin with

2023-11-14 10:37 UTC, sksadjad commented on packages/ssi-react/src/components/views/SSITableView/index.tsx
> +const getCellFormatting = (type: TableCellType, value: any, truncationLength?: number, enableHover?: boolean): ReactElement => {
modified ColumnHeader and made an options interface for the options we have (truncationLength & enableHover)

2023-11-14 10:38 UTC, sksadjad commented on packages/ssi-react/src/components/views/SSITableView/index.tsx
> +const getCellFormatting = (type: TableCellType, value: any, truncationLength?: number, enableHover?: boolean): ReactElement => {
modified ColumnHeader and made an options interface for the options we have (truncationLength & enableHover). added default value `false` to enableHover option

2023-11-14 11:29 UTC, BtencateSphereon commented on packages/ssi-react/src/components/fields/SSIHoverText/index.tsx
> +import {ColumnHeaderTextOptions} from '../../../types'
why not name this ColumnHeaderOptions?

2023-11-14 11:29 UTC, BtencateSphereon commented on packages/ssi-react/src/components/fields/SSIHoverText/index.tsx
> +  opts?: ColumnHeaderTextOptions
i would revert this and only pass in needed props. as the options might contain way more

2023-11-14 11:30 UTC, BtencateSphereon commented on packages/ssi-react/src/components/fields/SSIHoverText/index.tsx
> +  opts?: ColumnHeaderTextOptions
also SSIHoverText should have no notion of a column header

2023-11-14 11:31 UTC, BtencateSphereon commented on packages/ssi-react/src/types/table/index.ts
> +export interface ColumnHeaderTextOptions {
why not name this ColumnHeaderOptions? we can always decide to make specific options within this for text (if needed)

2023-11-14 11:36 UTC, BtencateSphereon commented on packages/ssi-react/src/components/fields/SSIHoverText/index.tsx
> +  const {truncationLength, enableHover = false} = opts
small remark, but i had this issue before as well where something being deconstructed is optional. I think it would be nicer to do something like:

const {truncationLength, enableHover = false} = props.opts ?? {}

2023-11-14 14:14 UTC, sksadjad commented on packages/ssi-react/src/components/fields/SSIHoverText/index.tsx
> +  opts?: ColumnHeaderTextOptions
reverted this

2023-11-14 14:14 UTC, sksadjad commented on packages/ssi-react/src/types/table/index.ts
> +export interface ColumnHeaderTextOptions {
changed the name to ColumnHeaderOptions

2023-11-14 14:15 UTC, sksadjad commented on packages/ssi-react/src/components/fields/SSIHoverText/index.tsx
> +  const {truncationLength, enableHover = false} = opts
had a lengthy discussion about this with you and changed it

2023-11-15 07:08 UTC, sksadjad commented on packages/ssi-react/src/components/fields/SSIHoverText/index.tsx
> +  truncationLength?: number | undefined
yeah I expected to behave like you say, but my IDE complains about it in the SSITableView/index.tsx: `Type number | undefined is not assignable to type number`

2023-11-15 07:09 UTC, sksadjad commented on packages/ssi-react/src/components/fields/SSIHoverText/index.tsx
> +  const {truncationLength, enableHover = false} = opts
removed this part, as we don't pass the options object to this anymore

2023-11-15 08:42 UTC, BtencateSphereon commented on packages/ssi-react/src/components/fields/SSIHoverText/index.tsx
> +  truncationLength?: number | undefined
i cannot do anything with this answer, as you did not investigate why it is complaining.

2023-11-15 09:24 UTC, BtencateSphereon approved these changes

2023-11-15 10:38 UTC, merged