feature/DPP-94
Sphereon-Opensource/UI-Components pull request #33
Opened 2023-11-27 09:16 UTC by BtencateSphereon

2023-11-29 21:41 UTC, nklomp requested changes
Small naming issue + question about the fixed colors

2023-11-29 21:41 UTC, nklomp commented on packages/core/src/styles/ssi/colors.ts
>  export const elements: Record<Element, string> = {
elementColors? It only contains colors. We also have fontColors

2023-11-29 21:41 UTC, nklomp commented on packages/ssi-react/src/components/indicators/ProgressStepIndicator/index.tsx
> +const getStepRowElement = (stepNumber: number, status: StepStatus, step: ProgressIndicatorStep, maxSteps: number) => {
No optional style/props instead of the fixed colors used in the component?

2023-11-30 09:27 UTC, BtencateSphereon commented on packages/core/src/styles/ssi/colors.ts
>  export const elements: Record<Element, string> = {
elementColors are colors for ui elements (divs) that we do not have a proper place for. i ran out of names. i do not want to mix these with font colors as then we can have font colors that should not be font colors

2023-11-30 10:00 UTC, BtencateSphereon commented on packages/ssi-react/src/components/indicators/ProgressStepIndicator/index.tsx
> +const getStepRowElement = (stepNumber: number, status: StepStatus, step: ProgressIndicatorStep, maxSteps: number) => {
Where do we want this to end? we have different kind of background colors, font colors, we have different kind of step markers, do we want to be able to be styled individually? do we want to be able to style the colors of borders?

2023-11-30 10:03 UTC, BtencateSphereon commented on packages/core/src/styles/ssi/colors.ts
>  export const elements: Record<Element, string> = {
example is the grey transition line used in this component. where would i place such color? i don't think it makes sense to start using a font color for this

2023-12-04 15:12 UTC, merged