Feature/dpp 125
Sphereon-Opensource/UI-Components pull request #38
Opened 2024-02-02 09:02 UTC by sksadjad

Added action group to Tables. Now if `actionGroup` is provided in the table properties, we see a new column in the table which has a bitterballen button and when clicked on will show all the provided actions

2024-02-05 10:16 UTC, maikel-maas commented on packages/ssi-react/src/components/buttons/RowActionMenuButton/index.tsx
> +      <SSIIconButton icon={icon || ButtonIcon.BITTERBALLEN} color={color} onClick={toggleDropdown} />
Two different default icons. Is this correct?

2024-02-05 10:24 UTC, maikel-maas commented on packages/ssi-react/src/components/buttons/RowActionMenuButton/index.tsx
> +    const handleClickOutside = (event: MouseEvent) => {
Not sure if the events should be handled here.

2024-02-05 10:27 UTC, maikel-maas commented on packages/ssi-react/src/components/buttons/SSIIconButton/index.tsx
> +  onClick: MouseEventHandler
If you change a property you may be breaking something

2024-02-05 10:27 UTC, maikel-maas requested changes
Left some comments

2024-02-07 07:52 UTC, BtencateSphereon requested changes

2024-02-07 07:52 UTC, BtencateSphereon commented on packages/core/src/types/button/index.ts
> +  BITTERBALLEN = 'bitterballen',
this is the dutch name

2024-02-07 07:52 UTC, BtencateSphereon commented on packages/ssi-react/src/components/assets/icons/BitterballenIcon/index.tsx
> +      <svg width="42" height="43" viewBox="0 0 42 43" fill={color} xmlns="http://www.w3.org/2000/svg">
look at other icons we have and make sure you do the same, i see you forgetting to set the correct values a lot here

2024-02-07 07:52 UTC, BtencateSphereon commented on packages/ssi-react/src/components/assets/icons/BitterballenIcon/index.tsx
> +    <div style={{...style, width: size, aspectRatio: 1, display: 'flex'}}>
should not flex

2024-02-07 07:52 UTC, BtencateSphereon commented on packages/ssi-react/src/components/assets/icons/DeleteIcon/index.tsx
> +    <div style={{...style, width: size, aspectRatio: 1, display: 'flex'}}>
are you sure these sizes are correct?

2024-02-07 07:52 UTC, BtencateSphereon commented on packages/ssi-react/src/styles/components/components/RowActionMenuButton/index.ts
> +export const ActionItemCaptionStyled = styled.span`
we have fonts you need to use

2024-02-07 07:52 UTC, BtencateSphereon commented on packages/ssi-react/src/types/table/index.ts
> +export type ActionGroup<T> = {
name is not specific enough

2024-02-07 07:52 UTC, BtencateSphereon commented on packages/ssi-react/src/types/table/index.ts
> +export type ActionButton<T> = {
name is not specific enough

2024-02-07 07:52 UTC, BtencateSphereon commented on packages/ssi-react/src/components/buttons/SSIIconButton/index.tsx
> +    case ButtonIcon.BITTERBALLEN:
this is the dutch name

2024-02-07 07:52 UTC, BtencateSphereon commented on packages/ssi-react/src/components/assets/icons/BitterballenIcon/index.tsx
> +const BitterballenIcon: FC<Props> = (props: Props): ReactElement => {
this is the dutch name

2024-02-07 07:52 UTC, BtencateSphereon commented on packages/ssi-react/src/components/buttons/RowActionMenuButton/index.tsx
> +  actions: ActionButton<T>[]
we use Array<> in this project

2024-02-07 07:52 UTC, BtencateSphereon commented on packages/ssi-react/src/components/buttons/RowActionMenuButton/index.tsx
> +    event?.stopPropagation()
do you need this?

2024-02-07 07:52 UTC, BtencateSphereon commented on packages/ssi-react/src/components/buttons/RowActionMenuButton/index.tsx
> +  const renderDropdown = (): ReactElement => {
why is this a function? should this not be a component? and check if we do not already have a dropdown, because we do. and then the question becomes, did maria design the same one? if not ask her why

because we want consistency between the designs

2024-02-07 07:52 UTC, BtencateSphereon commented on packages/ssi-react/src/components/buttons/RowActionMenuButton/index.tsx
> +    const handleClickOutside = (event: MouseEvent) => {
onClickOutside

2024-02-07 07:52 UTC, BtencateSphereon commented on packages/ssi-react/src/components/buttons/RowActionMenuButton/index.tsx
> +    event.stopPropagation()
do we need this?

2024-02-07 07:52 UTC, BtencateSphereon commented on packages/ssi-react/src/components/buttons/RowActionMenuButton/index.tsx
> +      <SSIIconButton icon={icon || ButtonIcon.BITTERBALLEN} color={color} onClick={toggleDropdown} />
ye this does not make sense

2024-02-07 08:25 UTC, sksadjad commented on packages/ssi-react/src/components/buttons/RowActionMenuButton/index.tsx
> +    event.stopPropagation()
yes. we have a `onRowClick` action for clicking on the whole row. this will prevent invoking that action

2024-02-16 14:44 UTC, sksadjad commented on packages/ssi-react/src/components/buttons/RowActionMenuButton/index.tsx
> +    const handleClickOutside = (event: MouseEvent) => {
changed the name to `onClickOutside`

2024-02-16 14:45 UTC, sksadjad commented on packages/ssi-react/src/components/buttons/RowActionMenuButton/index.tsx
> +  const renderDropdown = (): ReactElement => {
this opened a new area to this ticket, and as a result, I ported the functionality from the mobile-wallet to this repo (just the ssi-react) and used that

2024-02-16 14:46 UTC, sksadjad commented on packages/ssi-react/src/components/buttons/RowActionMenuButton/index.tsx
> +    event?.stopPropagation()
yes we need this. especially in the documents where we have a onRowClick functionality (this functionality will be added to credential list too)

2024-02-16 14:46 UTC, sksadjad commented on packages/core/src/types/button/index.ts
> +  BITTERBALLEN = 'bitterballen',
changed to meatballs

2024-02-16 14:47 UTC, sksadjad commented on packages/ssi-react/src/components/assets/icons/BitterballenIcon/index.tsx
> +      <svg width="42" height="43" viewBox="0 0 42 43" fill={color} xmlns="http://www.w3.org/2000/svg">
added height and width, removed size and changed the values here

2024-02-16 14:48 UTC, sksadjad commented on packages/ssi-react/src/components/buttons/RowActionMenuButton/index.tsx
> +      <SSIIconButton icon={icon || ButtonIcon.BITTERBALLEN} color={color} onClick={toggleDropdown} />
changed and made the MEATBALLS icon as the default one

2024-02-16 14:48 UTC, sksadjad commented on packages/ssi-react/src/components/buttons/RowActionMenuButton/index.tsx
> +    const handleClickOutside = (event: MouseEvent) => {
changed how we're handling onClickOutside

2024-02-16 14:52 UTC, sksadjad commented on packages/ssi-react/src/components/buttons/SSIIconButton/index.tsx
> +  onClick: MouseEventHandler
I need this change because I have to add `event.stopPropagation` when we have defined onRowClick for the tables

2024-02-16 14:57 UTC, sksadjad commented on packages/ssi-react/src/components/assets/icons/BitterballenIcon/index.tsx
> +    <div style={{...style, width: size, aspectRatio: 1, display: 'flex'}}>
removed the flex

2024-02-16 14:58 UTC, sksadjad commented on packages/ssi-react/src/components/assets/icons/DeleteIcon/index.tsx
> +const DeleteIcon: FC<Props> = (props: Props): ReactElement => {
removed the flex and changed the size for height and width

2024-02-16 14:58 UTC, sksadjad commented on packages/ssi-react/src/components/assets/icons/DeleteIcon/index.tsx
> +    <div style={{...style, width: size, aspectRatio: 1, display: 'flex'}}>
sizes are 21/19 according to design file. also removed the size, aspectRatio

2024-02-16 14:59 UTC, sksadjad commented on packages/ssi-react/src/components/assets/icons/DeleteIcon/index.tsx
> +  const {size = 21, color = fontColors.dark, style} = props
it's now 21/19 (according to design)

2024-02-16 14:59 UTC, sksadjad commented on packages/ssi-react/src/components/assets/icons/BitterballenIcon/index.tsx
> +      <svg width="42" height="43" viewBox="0 0 42 43" fill={color} xmlns="http://www.w3.org/2000/svg">
changed to 20/20

2024-02-16 15:00 UTC, sksadjad commented on packages/ssi-react/src/components/assets/icons/BitterballenIcon/index.tsx
> +  const {size = 42, color = fontColors.dark, style} = props
removed size and added height/width: 20/20

2024-02-16 15:00 UTC, sksadjad commented on packages/ssi-react/src/components/assets/icons/DeleteIcon/index.tsx
> +          fill="#D74500"
it's now set

2024-02-16 15:01 UTC, sksadjad commented on packages/ssi-react/src/components/assets/icons/DeleteIcon/index.tsx
> +  const {size = 21, color = fontColors.dark, style} = props
it's now 21/19

2024-02-16 15:01 UTC, sksadjad commented on packages/ssi-react/src/components/buttons/RowActionMenuButton/index.tsx
> +const RowActionMenuButton = <T,>({actions, icon, color, style = {}, rowData}: Props<T>): ReactElement => {
this is removed now, but in other places it's deconstructed

2024-02-16 15:03 UTC, sksadjad commented on packages/ssi-react/src/types/table/index.ts
> +  actions: ActionButton<T>[]
changed array types to use `Array`

2024-02-16 15:04 UTC, sksadjad commented on packages/ssi-react/src/components/views/SSITableView/index.tsx
> +  if (actionGroup) {
after our discussion removed this, and instead added it like a regular column (with a new type of course)

2024-02-16 15:05 UTC, sksadjad commented on packages/ssi-react/src/styles/components/components/RowActionMenuButton/index.ts
> +  background-color: #fff;
changed this to read from colors

2024-02-16 15:05 UTC, sksadjad commented on packages/ssi-react/src/styles/components/components/RowActionMenuButton/index.ts
> +  background: #fbfbfb;
changed this to read from colors

2024-02-16 15:06 UTC, sksadjad commented on packages/ssi-react/src/styles/components/components/RowActionMenuButton/index.ts
> +  width: auto;
removed `width:auto`

2024-02-16 15:07 UTC, sksadjad commented on packages/ssi-react/src/styles/components/components/RowActionMenuButton/index.ts
> +  letter-spacing: 0em;
removed

2024-02-16 15:24 UTC, sksadjad commented on packages/ssi-react/src/styles/components/components/RowActionMenuButton/index.ts
> +export const ActionItemCaptionStyled = styled.span`
changed to use font

2024-02-16 15:25 UTC, sksadjad commented on packages/ssi-react/src/styles/components/components/RowActionMenuButton/index.ts
> +export const ActionItemCaptionStyled = styled.span`
changed to use font

2024-02-16 15:26 UTC, sksadjad commented on packages/ssi-react/src/types/table/index.ts
> +export type ActionGroup<T> = {
this is removed. I'm now using the DropDownList and DropDownListItem the same way we're handling it in the mobile-wallet

2024-02-16 15:31 UTC, sksadjad commented on packages/ssi-react/src/components/fields/SSIHoverText/index.tsx
> +  const value = truncationLength && text ? text.substring(0, truncationLength) : text
text is effectively optional. meaning there are some cases that we don't have the necessary data to fill up a column (this specific case is the assetId in document table which don't have any assetId because the document is orphan). so changed the text to be optional and populated it with empty string in the props deconstruction

2024-02-16 15:31 UTC, sksadjad commented on packages/ssi-react/src/components/buttons/SSIIconButton/index.tsx
> +    case ButtonIcon.BITTERBALLEN:
changed to meatballs

2024-02-16 15:34 UTC, sksadjad commented on packages/ssi-react/src/components/buttons/SSIIconButton/index.tsx
> +  onClick: MouseEventHandler
this is because I needed the event to stopPropagation. We have tables with the action onRowClick. so I have to add this in order to prevent calling onRowClick whenever we call the meatballs or the action in the menu

2024-02-16 15:34 UTC, sksadjad commented on packages/ssi-react/src/components/assets/icons/BitterballenIcon/index.tsx
> +const BitterballenIcon: FC<Props> = (props: Props): ReactElement => {
changed to meatballs

2024-02-16 15:34 UTC, sksadjad commented on packages/ssi-react/src/components/buttons/RowActionMenuButton/index.tsx
> +  actions: ActionButton<T>[]
changed to array

2024-02-20 11:24 UTC, BtencateSphereon commented on packages/ssi-react/src/components/assets/icons/MeatBallsIcon/index.tsx
> +      <svg width="20" height="20" viewBox="0 0 32 32" fill={color} xmlns="http://www.w3.org/2000/svg">
width and height values are incorrect, they should be 100% so they can scale

2024-02-20 11:24 UTC, BtencateSphereon commented on packages/ssi-react/src/components/assets/icons/DeleteIcon/index.tsx
> +      <svg width="20" height="21" viewBox="0 0 20 21" fill={color} xmlns="http://www.w3.org/2000/svg">
width and height values are incorrect, they should be 100% so they can scale

2024-02-20 11:25 UTC, BtencateSphereon commented on packages/ssi-react/src/components/fields/SSIHoverText/index.tsx
> +  text?: string
why did you make this change?

2024-02-20 11:28 UTC, BtencateSphereon commented on packages/ssi-react/src/types/button/index.ts
> +export type GeneralButton = Button | TableColumnActionButton
i dont like this type, why do we need this?

2024-02-20 11:28 UTC, BtencateSphereon commented on packages/ssi-react/src/components/views/SSITableView/SSITableViewHeader/index.tsx
> +          {/*{enableMostRecent && (
why is this stuff now disabled?

2024-02-20 12:14 UTC, sksadjad commented on packages/ssi-react/src/components/assets/icons/BitterballenIcon/index.tsx
> +    <div style={{...style, width: size, aspectRatio: 1, display: 'flex'}}>
added back the flex

2024-02-21 08:41 UTC, BtencateSphereon approved these changes

2024-02-21 09:03 UTC, merged