feature/CWALL-121
Sphereon-Opensource/UI-Components pull request #40
Opened 2024-02-27 12:36 UTC by BtencateSphereon

2024-02-27 21:46 UTC, nklomp requested changes
Some small remarks, questions

2024-02-27 21:46 UTC, nklomp commented on packages/ssi-react/src/components/views/SSITableView/index.tsx
> +  const onRowSelectionChange: OnChangeFn<RowSelectionState> = (updatedRowSelection): void => {
Can't we type this argument?

I am assuming that is also why the next ts-ignore is present.

2024-02-27 21:46 UTC, nklomp commented on packages/ssi-react/src/components/views/SSITableView/index.tsx
> +    for (const key in currentRowSelection) {
Is there a reason for a traditional loop? Could be quite easily mapped from the looks of it

2024-02-28 09:10 UTC, BtencateSphereon commented on packages/ssi-react/src/components/views/SSITableView/index.tsx
> +  const onRowSelectionChange: OnChangeFn<RowSelectionState> = (updatedRowSelection): void => {
Added type and a comment. It's complaining about something i have no solution for yet and did not want to spend more time on it

2024-02-28 22:31 UTC, nklomp approved these changes
LGTM

2024-02-29 08:38 UTC, merged