feature/CWALL-148
Sphereon-Opensource/UI-Components pull request #41
Opened 2024-03-06 22:22 UTC by BtencateSphereon

2024-03-06 23:38 UTC, nklomp commented on packages/core/src/utils/FileUtils.ts
> +    const byteCharacters = atob(base64Parts[1]);
Hmzz, this is probably not portable to RN

You can just use uint8arrays with the fromString method and base64 encoding arguments. That should also eliminate the need for the next 2 lines

2024-03-06 23:40 UTC, nklomp commented on packages/core/src/utils/FileUtils.ts
> +    const blob = new Blob([byteArray], { type: contentType });
This and next line is probably also not portable to RN. Is this method really needed in core? Or can it be moved to react?

2024-03-06 23:43 UTC, nklomp commented on packages/core/src/utils/FileUtils.ts
> +    const base64Parts = base64.split(';base64,');
By the looks of it you are splitting a data URI that uses base64 encoding. Suggest to rename the method, as base64 alone assumes I can pass a base64 file contents for instance

2024-03-06 23:46 UTC, nklomp commented on packages/ssi-react/src/components/fields/ComboBox/index.tsx
> +        formatCreateLabel: (inputValue: string) => `${inlineOption.caption}`,
Why is the arg required?

2024-03-06 23:47 UTC, nklomp commented on packages/ssi-react/src/components/fields/DragAndDropBox/index.tsx
> +    const file: File | undefined = event.target.files?.[0]
Probably wise to add a fixme, for multiple file support to this file

2024-03-06 23:48 UTC, nklomp commented on packages/ssi-react/src/components/fields/FileSelection/index.tsx
> +  {label: 'Public', value: 'public'},
i18n?

2024-03-06 23:49 UTC, nklomp commented on packages/ssi-react/src/components/fields/FileSelection/index.tsx
> +const getFileSizeDisplay = (bytes: number): string => {
Suggest to move this to core. Can be used in RN as well

2024-03-06 23:52 UTC, nklomp commented on packages/ssi-react/src/components/fields/JSONForms/PassportPhotoControl/index.tsx
> +                const base64Parts = result.split(';base64,');
I think we could make some small utility functions for these in core. As I already expected in a previous comment, these are data URIs; so getting the base64 part and mimetype are probably useful elsewhere in the future as well

2024-03-10 20:13 UTC, BtencateSphereon commented on packages/core/src/utils/FileUtils.ts
> +    const byteCharacters = atob(base64Parts[1]);
refactored using uint8arrays

2024-03-10 20:13 UTC, BtencateSphereon commented on packages/core/src/utils/FileUtils.ts
> +    const blob = new Blob([byteArray], { type: contentType });
refactored using uint8arrays

2024-03-10 20:14 UTC, BtencateSphereon commented on packages/ssi-react/src/components/fields/ComboBox/index.tsx
> +        formatCreateLabel: (inputValue: string) => `${inlineOption.caption}`,
removed. this component needs work anyways

2024-03-10 20:14 UTC, BtencateSphereon commented on packages/ssi-react/src/components/fields/DragAndDropBox/index.tsx
> +    const file: File | undefined = event.target.files?.[0]
added fixme

2024-03-10 20:14 UTC, BtencateSphereon commented on packages/ssi-react/src/components/fields/FileSelection/index.tsx
> +  {label: 'Public', value: 'public'},
added

2024-03-10 20:14 UTC, BtencateSphereon commented on packages/ssi-react/src/components/fields/FileSelection/index.tsx
> +const getFileSizeDisplay = (bytes: number): string => {
moved

2024-03-10 20:14 UTC, BtencateSphereon commented on packages/ssi-react/src/components/fields/JSONForms/PassportPhotoControl/index.tsx
> +                const base64Parts = result.split(';base64,');
function created in the core package

2024-03-12 23:32 UTC, nklomp requested changes
See remark about TS support for uint8arrays

2024-03-12 23:32 UTC, nklomp commented on packages/ssi-react/src/@types/index.d.ts
> +declare module 'uint8arrays' {
Why is this needed? uint8arrays hat type maps, so it should be supported in a TS env. We never had issues with this package and version before. So maybe a tsconfig isssue in case it is causing issues now

2024-03-13 08:29 UTC, BtencateSphereon commented on packages/ssi-react/src/@types/index.d.ts
> +declare module 'uint8arrays' {
i dont know, it started to complain there were no type definitions

2024-03-14 12:21 UTC, nklomp commented on packages/ssi-react/src/@types/index.d.ts
> +declare module 'uint8arrays' {
Hmzz, strange. Probably something with nodenext resolution. Not going to spend time on this now

2024-03-14 12:21 UTC, nklomp approved these changes

2024-03-14 12:43 UTC, merged