feature/CWALL-145
Sphereon-Opensource/UI-Components pull request #44
Opened 2024-04-01 20:37 UTC by BtencateSphereon

2024-04-08 22:09 UTC, sanderPostma commented on packages/core/src/utils/ImageUtils.ts
> +export const isBase64ImageUri = (value: unknown): boolean => {
Does does not guarantee a base64 URI
Maybe like this
```
export const isBase64ImageUri = (value: unknown): boolean => {
  if (typeof value !== 'string') {
    return false;
  }

  const base64Pattern = /^data:image\/[a-zA-Z]+;base64,[A-Za-z0-9+\/_-]*(={0,2})?$/;
  return base64Pattern.test(value);
}
```
where base64Pattern can be moved to a global static scope

2024-04-08 23:01 UTC, sanderPostma requested changes

2024-04-10 08:48 UTC, BtencateSphereon commented on packages/ssi-react/src/components/views/JSONDataView/index.tsx
> +    const expandNodeInitially = typeof shouldExpandNodeInitially === 'function' ? shouldExpandNodeInitially : () => shouldExpandNodeInitially
useMemo should be used for expensive calculations and maybe some special cases to avoid re-renders. This is just a ternary that turns a boolean into a function based on the props.

2024-04-10 08:52 UTC, BtencateSphereon commented on packages/core/src/utils/TypeUtils.ts
> +            return null
correct. removed

2024-04-10 09:08 UTC, BtencateSphereon commented on packages/ssi-react/src/components/views/JSONDataView/index.tsx
> +                const dimensions = await getImageSize(base64Uri);
then it will be treated as just a string. for now i would say that is ok. the input does need to be correct to display an image.

2024-04-10 09:23 UTC, BtencateSphereon commented on packages/core/src/utils/ImageUtils.ts
> +    return /^data:image\//.test(value)
yes, i guess this one is safer. good catch

2024-04-11 09:21 UTC, merged