Feature/cwall 200
Sphereon-Opensource/UI-Components pull request #50
Opened 2024-06-03 12:46 UTC by sksadjad

added credential-branding module

2024-06-05 09:21 UTC, maikel-maas commented on packages/credential-branding/src/mapping/CredentialMapper.ts
> +  // TODO: bring this back. This checks if the activeUser has the matching correlationId.
Place a link to a ticket in the TODO or remove it

2024-06-05 09:22 UTC, maikel-maas commented on packages/credential-branding/src/mapping/CredentialMapper.ts
> +      // FIXME disabled this to not show keys of objects
Place a link to a ticket in the TODO or remove it. Remove the commented-out code as well

2024-06-05 09:22 UTC, maikel-maas commented on packages/credential-branding/src/mapping/CredentialMapper.ts
> +    // todo: Probably still wise to allow a user to override it
Place a link to a ticket in the TODO or remove it

2024-06-05 09:23 UTC, maikel-maas commented on packages/credential-branding/src/mapping/CredentialMapper.ts
> +    //TODO: bring back the react-native related code
Place a link to a ticket in the TODO or remove it.

2024-06-05 09:25 UTC, maikel-maas commented on packages/credential-branding/src/utils/MappingUtils.ts
> +  // TODO implement
Place a link to a ticket in the TODO or remove it. Remove the commented-out code as well

2024-06-05 09:26 UTC, maikel-maas requested changes
Left some remarks

2024-06-05 11:28 UTC, nklomp commented on packages/credential-branding/src/services/ReactNativeImagePreloader.ts
> +    /*FastImage.preload(sources)*/
No don't if this is literally the correct code but needs to be moved

2024-06-05 11:30 UTC, nklomp commented on packages/credential-branding/src/mapping/CredentialMapper.ts
> +  // TODO: bring this back. This checks if the activeUser has the matching correlationId.
No don't if this is literally the correct code but needs to be moved. It needs to live somewhere so the person picking it up knows what the code was and what to do with it. This is entirely different from some old code. We simply have a TODO here

2024-06-05 11:31 UTC, nklomp reviewed
@maikel-maas  You are correct that it needs to be linked to a ticket. But this is not a case of removing the code. The ticket would litteraly be about making it work again in RN. Then removing all code occurances, only makes it way harder. This is not some comments of old/dead code that should go

2024-06-05 11:33 UTC, nklomp commented on packages/credential-branding/LICENSE
What is this license doing here? Should be apache2

2024-06-05 11:33 UTC, nklomp commented on packages/credential-branding/package.json
> +  "license": "Apache-2.0",
Okay, next time be more careful with licensense. This is mentioning Apache2 as it should, but you included an actual GPL license

2024-06-05 11:33 UTC, nklomp commented on packages/credential-branding/README.md
> +**Warning: This package still is in every early development. Breaking changes without notice will happen at this point!**
Remove this line altogether please

2024-06-05 11:39 UTC, nklomp reviewed
For next time please ring the bell earlier. We have way too many things todo to be working on this a few days and then not have the full solution to begin with. The better approach would have been to discuss creating a copy make it work for web only and create a ticket to refactor it making it available for both. Obviously a shared package should not all of a sudden start creating RN instances etc

2024-06-05 11:39 UTC, nklomp commented on packages/credential-branding/src/mapping/CredentialMapper.ts
> +    // todo: Probably still wise to allow a user to override it
Not every todo needs a ticket. It is nice if we create one. But this is a perfect example of a TODO that doesn't necessarily need a ticket. Every FIXME needs one

2024-06-05 12:55 UTC, sksadjad commented on packages/credential-branding/LICENSE
yeah replaced it

2024-06-05 13:01 UTC, sksadjad commented on packages/credential-branding/src/mapping/CredentialMapper.ts
> +    //TODO: bring back the react-native related code
added

2024-06-07 15:07 UTC, nklomp commented on packages/core/LICENSE
> -# GNU GENERAL PUBLIC LICENSE
Apache2 license

2024-06-07 15:08 UTC, nklomp commented on packages/core/LICENSE
> +   Copyright [2023] [Sphereon BV]
```suggestion
   Copyright [2024] [Sphereon International B.V.]
```

2024-06-07 15:11 UTC, merged